### ISSUE TITLE
Cant access every playlist when you have more than ca. 7

### ISSUE THREAD

**Issue by thojo0** [rithik-b/PlaylistLoaderPlugin#15]
You cant scroll to the other Playlists

**Comment by rithik-b** [comment]
You can, just use the thumbstick on your controller or touchpad on vive.
Index user? Please read the readme for instructions!

**Comment by thojo0** [comment]
Sorry didn't saw it.
Thx.

**Comment by AngelKing86** [comment]
I think some users have this problem from DynamicOpenVR Mod. So you are not able to change the Key Binding in Legacy Mode, if you have installed this mod.

Please see this open issue Thumbstick actions
https://github.com/nicoco007/DynamicOpenVR/issues/35

**Comment by timdonovanuk** [comment]
I stumbled across this via github. Such a crazy esoteric route to figure out why I couldn't browse playlists. How come this isn't more well known? BTW, rather than a complex video that doesn't actually map to to value index controllers (although it's appreciated), you could just show this, where there are plenty of community made bindings that (probably work). One of them is even called "playlist scrolling fix"! :)
![image](https://user-images.githubusercontent.com/8156439/100526663-f9d78680-31c2-11eb-8ec5-e674c48b1ce0.png)

**Comment by AngelKing86** [comment]
I also had the problem with the playlist. But for me it was because DynamicOpenVR.BeatSaber set the bindings. This issue has been fixed there.

https://github.com/nicoco007/DynamicOpenVR/issues/35#issuecomment-734123080

Otherwise, it is a general problem between BeatSaber and the Index Controllers Bindings. Unfortunately, you have to change the bindings in order to be able to scroll in the playlists.

**Comment by timdonovanuk** [comment]
@AngelKing86 indeed...or just select the bindings someone else already made! It's a 5 second job vs 5 min.
